[package]
name = "tessara-api"
version = "0.1.0"
edition = "2024"

[features]
default = []
ssr = ["tessara-web/ssr"]

[dependencies]
anyhow = { workspace = true }
argon2 = { workspace = true }
arrow = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
datafusion = { workspace = true }
password-hash = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
tessara-core = { path = "../tessara-core" }
tessara-data-ops = { path = "../tessara-data-ops" }
tessara-datasets = { path = "../tessara-datasets" }
tessara-dashboards = { path = "../tessara-dashboards" }
tessara-forms = { path = "../tessara-forms" }
tessara-hierarchy = { path = "../tessara-hierarchy" }
tessara-module-contract = { path = "../tessara-module-contract" }
tessara-reference-scoped-records = { path = "../tessara-reference-scoped-records" }
tessara-submissions = { path = "../tessara-submissions" }
tessara-web = { path = "../tessara-web", default-features = false }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
