[package]
name = "tessara-web-data-ops"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
hydrate = [
    "leptos/hydrate",
]
ssr = [
    "leptos/ssr",
]

[dependencies]
icons = { workspace = true }
leptos = { workspace = true }
tessara-web-ui = { path = "../tessara-web-ui" }
