[package]
name = "tessara-components-contract"
version = "2.0.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
tessara-module-contract = { path = "../tessara-module-contract" }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
semver = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
