[package]
name = "tessara-web-components"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
hydrate = [
    "leptos/hydrate",
    "tessara-web-component-viewer/hydrate",
    "tessara-web-http/hydrate",
]
ssr = [
    "leptos/ssr",
    "tessara-web-component-viewer/ssr",
]

[dependencies]
gloo-net = { workspace = true }
icons = { workspace = true }
leptos = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tessara-web-component-viewer = { path = "../tessara-web-component-viewer", default-features = false }
tessara-web-data-ops = { path = "../tessara-web-data-ops" }
tessara-web-http = { path = "../tessara-web-http", default-features = false }
tessara-module-ui = { path = "../tessara-module-ui", features = ["components"] }
web-sys = { workspace = true }
