[package]
name = "tessara-dashboards"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tessara-components-contract = { path = "../tessara-components-contract" }
tessara-module-contract = { path = "../tessara-module-contract" }
thiserror = { workspace = true }
uuid = { workspace = true }
