[package]
name = "tessara-web-ui"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
hydrate = [
    "leptos/hydrate",
]
ssr = [
    "leptos/ssr",
]

[dependencies]
icons = { workspace = true }
js-sys = { workspace = true }
leptos = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
